### ISSUE TITLE
Inconsistent IDs

### ISSUE THREAD

**Issue by jose** [MattePalte/Bugs-Quantum-Computing-Platforms#1]
Hi @MattePalte,

It seems there are some inconsistent IDs in the [`annotation_bugs.csv`](https://github.com/MattePalte/Bugs-Quantum-Computing-Platforms/blob/main/artifacts/annotation_bugs.csv) file.  In the `id` column there are non-numeric ids: "75,5", "1814,5", "1854,5", "1900,5", and "1909,5".  Is this ok or expected?

If one fixes those ids, i.e., removes the ",5" sufix, then one end up with duplicate IDs.

--
Best,
Jose

**Comment by MattePalte** [comment]
Hi Jose,
that is on purpose. When two bugs are fixed in the same commit, we use the convention of using the comma for the second bug. For example bug id 1900 fixes two bugs, then we add a new line with an ID 1900,5 for the second one, and we use 1900 for the first bug. We use this approach to have a way to track back to commits.

Best,
Matteo

**Comment by jose** [comment]
Ok.  Could you please add that info to the [README.md](https://github.com/MattePalte/Bugs-Quantum-Computing-Platforms/blob/main/README.md) file?


Best,
Jose

**Comment by MattePalte** [comment]
Done. Thanks again for the useful feedback,
Best,
Matteo
